### ISSUE TITLE
Provide source maps for build assets

### ISSUE THREAD

**Issue by gkjohnson** [takram-design-engineering/three-geospatial#6]
Right now there are no source maps for the built files making it difficult to debug and step through if there are issues or to see what's going on. Relatedly - how are the files built? I don't see a "build" script in the package.json and I'm less familiar with "nextjs" which it looks like is being used.

**Comment by shotamatsuda** [comment]
Good point, and I completely missed that! I’ll make sure to add source maps.

Since this is a monorepo, `nx` is used to manage and execute commands.

To build three-atmosphere, run `nx build atmosphere`. This runs `vite` with the config located in `packages/atmosphere`. The build output will be in `/dist/packages/atmosphere`.

Just to clarify, Next.js isn’t involved in building the packages.

**Comment by shotamatsuda** [comment]
Added in https://github.com/takram-design-engineering/three-geospatial/commit/a99277b304ca92c98d2dc8f6326c0d9c8aeed57a

**Comment by gkjohnson** [comment]
They work great, thanks!
